sudo: required
services:
  - docker

script:
  - echo "Build local image"
  - docker build -t ansible_playbook .
  - docker images
  - echo "Run local image"
  - ls -la
  - docker-compose -f docker-compose-dev.yml run --rm ansible remote.yml -i production
  - docker ps -a
  - echo "Testing public image on Docker Hub"
  - docker-compose run --rm ansible remote.yml -i production
  - docker ps -a
